# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_plotwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(606, 646)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_refresh_verticalLayout = QtWidgets.QVBoxLayout()
        self.plot_refresh_verticalLayout.setObjectName("plot_refresh_verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plot_refresh_verticalLayout.addItem(spacerItem)
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setObjectName("pause_button")
        self.plot_refresh_verticalLayout.addWidget(self.pause_button)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setObjectName("update_button")
        self.plot_refresh_verticalLayout.addWidget(self.update_button)
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setObjectName("settings_button")
        self.plot_refresh_verticalLayout.addWidget(self.settings_button)
        self.refreshtime_formLayout_5 = QtWidgets.QFormLayout()
        self.refreshtime_formLayout_5.setObjectName("refreshtime_formLayout_5")
        self.refresh_label = QtWidgets.QLabel(self.centralwidget)
        self.refresh_label.setObjectName("refresh_label")
        self.refreshtime_formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.refresh_label)
        self.refresh_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_lineEdit.sizePolicy().hasHeightForWidth())
        self.refresh_lineEdit.setSizePolicy(sizePolicy)
        self.refresh_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.refresh_lineEdit.setObjectName("refresh_lineEdit")
        self.refreshtime_formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.refresh_lineEdit)
        self.plot_refresh_verticalLayout.addLayout(self.refreshtime_formLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plot_refresh_verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.plot_refresh_verticalLayout, 3, 0, 1, 1)
        self.plotwidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.plotwidget.setObjectName("plotwidget")
        self.gridLayout.addWidget(self.plotwidget, 0, 1, 1, 1)
        self.xscale_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.xscale_tabWidget.setObjectName("xscale_tabWidget")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.history_verticalLayout = QtWidgets.QVBoxLayout()
        self.history_verticalLayout.setObjectName("history_verticalLayout")
        self.history_stopdate_label = QtWidgets.QLabel(self.history_tab)
        self.history_stopdate_label.setObjectName("history_stopdate_label")
        self.history_verticalLayout.addWidget(self.history_stopdate_label, 0, QtCore.Qt.AlignHCenter)
        self.history_stopdate_lineEdit = QtWidgets.QLineEdit(self.history_tab)
        self.history_stopdate_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.history_stopdate_lineEdit.setObjectName("history_stopdate_lineEdit")
        self.history_verticalLayout.addWidget(self.history_stopdate_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.history_length_label = QtWidgets.QLabel(self.history_tab)
        self.history_length_label.setObjectName("history_length_label")
        self.history_verticalLayout.addWidget(self.history_length_label, 0, QtCore.Qt.AlignHCenter)
        self.history_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.history_horizontalLayout_2.setObjectName("history_horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.history_horizontalLayout_2.addItem(spacerItem2)
        self.days_formLayout = QtWidgets.QFormLayout()
        self.days_formLayout.setObjectName("days_formLayout")
        self.days_label = QtWidgets.QLabel(self.history_tab)
        self.days_label.setObjectName("days_label")
        self.days_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.days_label)
        self.days_lineEdit = QtWidgets.QLineEdit(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days_lineEdit.sizePolicy().hasHeightForWidth())
        self.days_lineEdit.setSizePolicy(sizePolicy)
        self.days_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.days_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.days_lineEdit.setObjectName("days_lineEdit")
        self.days_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.days_lineEdit)
        self.history_horizontalLayout_2.addLayout(self.days_formLayout)
        self.hours_formLayout = QtWidgets.QFormLayout()
        self.hours_formLayout.setObjectName("hours_formLayout")
        self.hours_label = QtWidgets.QLabel(self.history_tab)
        self.hours_label.setObjectName("hours_label")
        self.hours_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hours_label)
        self.hours_lineEdit = QtWidgets.QLineEdit(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hours_lineEdit.sizePolicy().hasHeightForWidth())
        self.hours_lineEdit.setSizePolicy(sizePolicy)
        self.hours_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hours_lineEdit.setObjectName("hours_lineEdit")
        self.hours_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hours_lineEdit)
        self.history_horizontalLayout_2.addLayout(self.hours_formLayout)
        self.minutes_formLayout = QtWidgets.QFormLayout()
        self.minutes_formLayout.setObjectName("minutes_formLayout")
        self.minutes_label = QtWidgets.QLabel(self.history_tab)
        self.minutes_label.setObjectName("minutes_label")
        self.minutes_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.minutes_label)
        self.minutes_lineEdit = QtWidgets.QLineEdit(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minutes_lineEdit.sizePolicy().hasHeightForWidth())
        self.minutes_lineEdit.setSizePolicy(sizePolicy)
        self.minutes_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.minutes_lineEdit.setObjectName("minutes_lineEdit")
        self.minutes_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minutes_lineEdit)
        self.history_horizontalLayout_2.addLayout(self.minutes_formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.history_horizontalLayout_2.addItem(spacerItem3)
        self.history_verticalLayout.addLayout(self.history_horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.history_verticalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.history_verticalLayout)
        self.xscale_tabWidget.addTab(self.history_tab, "")
        self.range_tab = QtWidgets.QWidget()
        self.range_tab.setObjectName("range_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.range_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.range_startdate_label = QtWidgets.QLabel(self.range_tab)
        self.range_startdate_label.setObjectName("range_startdate_label")
        self.verticalLayout_4.addWidget(self.range_startdate_label, 0, QtCore.Qt.AlignHCenter)
        self.range_startdate_lineEdit = QtWidgets.QLineEdit(self.range_tab)
        self.range_startdate_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.range_startdate_lineEdit.setObjectName("range_startdate_lineEdit")
        self.verticalLayout_4.addWidget(self.range_startdate_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.range_stopdate_label = QtWidgets.QLabel(self.range_tab)
        self.range_stopdate_label.setObjectName("range_stopdate_label")
        self.verticalLayout_4.addWidget(self.range_stopdate_label, 0, QtCore.Qt.AlignHCenter)
        self.range_stopdate_lineEdit = QtWidgets.QLineEdit(self.range_tab)
        self.range_stopdate_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.range_stopdate_lineEdit.setText("")
        self.range_stopdate_lineEdit.setObjectName("range_stopdate_lineEdit")
        self.verticalLayout_4.addWidget(self.range_stopdate_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.xscale_tabWidget.addTab(self.range_tab, "")
        self.gridLayout.addWidget(self.xscale_tabWidget, 2, 1, 3, 1)
        self.yscale_options_verticalLayout = QtWidgets.QVBoxLayout()
        self.yscale_options_verticalLayout.setObjectName("yscale_options_verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.yscale_options_verticalLayout.addItem(spacerItem5)
        self.autoscale_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.autoscale_checkBox.setChecked(True)
        self.autoscale_checkBox.setObjectName("autoscale_checkBox")
        self.yscale_options_verticalLayout.addWidget(self.autoscale_checkBox)
        self.ylim_formLayout = QtWidgets.QFormLayout()
        self.ylim_formLayout.setObjectName("ylim_formLayout")
        self.ymax_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ymax_lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymax_lineEdit.sizePolicy().hasHeightForWidth())
        self.ymax_lineEdit.setSizePolicy(sizePolicy)
        self.ymax_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ymax_lineEdit.setObjectName("ymax_lineEdit")
        self.ylim_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ymax_lineEdit)
        self.ymax_label = QtWidgets.QLabel(self.centralwidget)
        self.ymax_label.setObjectName("ymax_label")
        self.ylim_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ymax_label)
        self.ymin_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymin_lineEdit.sizePolicy().hasHeightForWidth())
        self.ymin_lineEdit.setSizePolicy(sizePolicy)
        self.ymin_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ymin_lineEdit.setObjectName("ymin_lineEdit")
        self.ylim_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ymin_lineEdit)
        self.ymin_label = QtWidgets.QLabel(self.centralwidget)
        self.ymin_label.setObjectName("ymin_label")
        self.ylim_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ymin_label)
        self.yscale_options_verticalLayout.addLayout(self.ylim_formLayout)
        self.outlier_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.outlier_checkBox.setObjectName("outlier_checkBox")
        self.yscale_options_verticalLayout.addWidget(self.outlier_checkBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outlier_reject_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outlier_reject_label.sizePolicy().hasHeightForWidth())
        self.outlier_reject_label.setSizePolicy(sizePolicy)
        self.outlier_reject_label.setObjectName("outlier_reject_label")
        self.horizontalLayout_2.addWidget(self.outlier_reject_label)
        self.outlier_reject_level_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outlier_reject_level_lineEdit.sizePolicy().hasHeightForWidth())
        self.outlier_reject_level_lineEdit.setSizePolicy(sizePolicy)
        self.outlier_reject_level_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outlier_reject_level_lineEdit.setObjectName("outlier_reject_level_lineEdit")
        self.horizontalLayout_2.addWidget(self.outlier_reject_level_lineEdit)
        self.yscale_options_verticalLayout.addLayout(self.horizontalLayout_2)
        self.log_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.log_radioButton.setObjectName("log_radioButton")
        self.yscale_options_verticalLayout.addWidget(self.log_radioButton)
        self.lin_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.lin_radioButton.setChecked(True)
        self.lin_radioButton.setObjectName("lin_radioButton")
        self.yscale_options_verticalLayout.addWidget(self.lin_radioButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.yscale_options_verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.yscale_options_verticalLayout, 0, 0, 1, 1)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 26))
        self.menubar.setObjectName("menubar")
        PlotWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotWindow)
        self.xscale_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "MainWindow"))
        self.pause_button.setText(_translate("PlotWindow", "Pause"))
        self.update_button.setText(_translate("PlotWindow", "Update Data"))
        self.settings_button.setText(_translate("PlotWindow", "Update Settings"))
        self.refresh_label.setText(_translate("PlotWindow", "Refresh Time (s)"))
        self.refresh_lineEdit.setText(_translate("PlotWindow", "30"))
        self.history_stopdate_label.setText(_translate("PlotWindow", "Stop DateTime (yy/mm/dd hh:mm:ss) or \"now\""))
        self.history_stopdate_lineEdit.setText(_translate("PlotWindow", "now"))
        self.history_length_label.setText(_translate("PlotWindow", "Plot History Length"))
        self.days_label.setText(_translate("PlotWindow", "Days"))
        self.days_lineEdit.setText(_translate("PlotWindow", "1"))
        self.hours_label.setText(_translate("PlotWindow", "Hours"))
        self.hours_lineEdit.setText(_translate("PlotWindow", "0"))
        self.minutes_label.setText(_translate("PlotWindow", "Minutes"))
        self.minutes_lineEdit.setText(_translate("PlotWindow", "0"))
        self.xscale_tabWidget.setTabText(self.xscale_tabWidget.indexOf(self.history_tab), _translate("PlotWindow", "History Mode"))
        self.range_startdate_label.setText(_translate("PlotWindow", "Start Time (yy/mm/dd hh:mm:ss)"))
        self.range_stopdate_label.setText(_translate("PlotWindow", "Stop Time (yy/mm/dd hh:mm:ss) or \"now\""))
        self.xscale_tabWidget.setTabText(self.xscale_tabWidget.indexOf(self.range_tab), _translate("PlotWindow", "Range Mode"))
        self.autoscale_checkBox.setText(_translate("PlotWindow", "Autoscale"))
        self.ymax_lineEdit.setText(_translate("PlotWindow", "1"))
        self.ymax_label.setText(_translate("PlotWindow", "Ymax"))
        self.ymin_lineEdit.setText(_translate("PlotWindow", "0"))
        self.ymin_label.setText(_translate("PlotWindow", "Ymin"))
        self.outlier_checkBox.setText(_translate("PlotWindow", "Outlier Reject"))
        self.outlier_reject_label.setText(_translate("PlotWindow", "Outlier Reject Level:"))
        self.outlier_reject_level_lineEdit.setText(_translate("PlotWindow", "2"))
        self.log_radioButton.setText(_translate("PlotWindow", "Logarithmic"))
        self.lin_radioButton.setText(_translate("PlotWindow", "Linear"))
from plotwidget import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QMainWindow()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())
